server:
  port: 8283
spring:
  application:
    name: account-service
  profiles:
    include:
      - seata
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account?useSSL=false&serverTimezone=UTC
    username: root
    password: root
#    platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
