spring:
  application:
    name: business-service
  profiles:
#    active: dev
    include:
      - seata
server:
  port: 8284
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
  level:
    root: debug
